apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: agentic-chatbot-sep21-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rh-ee-lyoon-dh/agentic-chatbot-sep21-1:8fd8314522d50d8635ea314f9469757d276db0d7@sha256:1150cc5f63c8dc78ac2a8635e6ae493c27f6588bbd0528929d5bc3eef7aa7284 # use pre-built to bootstrap
          name: app-inference
